import fs from 'node:fs';

const file = 'electron/IntelligenceEngine.ts';
let s = fs.readFileSync(file, 'utf8');

const helperAnchor = "    // ── CONTEXT INTELLIGENCE V3 — shared adoption plumbing (Phase 6) ─────────\n";
const helper = `    /**\n     * Application-level mode retrieval boundary. Normal IntelligenceEngine\n     * retrieval must use the application-owned universal RAGManager; the\n     * governed EvidenceResolver seam remains the only intentional raw hybrid\n     * dependency.\n     */\n    private async retrieveUniversalModeContext(\n        query: string,\n        modeId?: string | null,\n        options: {\n            tokenBudget?: number;\n            topK?: number;\n            allowRerank?: boolean;\n            forceDocumentGrounding?: boolean;\n            answerType?: string;\n            followUpReferentHint?: string;\n        } = {},\n    ): Promise<string> {\n        const ragManager = this.ragManagerProvider?.() as any;\n        if (!ragManager || typeof ragManager.search !== 'function') return '';\n\n        try {\n            const response = await ragManager.search(query, {\n                selectedSources: ['mode-reference'],\n                allowedSources: ['mode-reference'],\n                modeId: modeId ?? undefined,\n                tokenBudget: options.tokenBudget ?? 1800,\n                ...(options.topK !== undefined ? { topK: options.topK } : {}),\n                ...(options.allowRerank !== undefined ? { allowRerank: options.allowRerank } : {}),\n                ...(options.forceDocumentGrounding !== undefined\n                    ? { forceDocumentGrounding: options.forceDocumentGrounding }\n                    : {}),\n                ...(options.answerType ? { answerType: options.answerType } : {}),\n                excludeCustomContext: true,\n                ...(options.followUpReferentHint\n                    ? { followUpReferentHint: options.followUpReferentHint }\n                    : {}),\n            });\n\n            if (response?.status !== 'ok' || !response.manualContext?.items?.length) return '';\n            const { renderManualContext } = require('./rag/ManualRenderContext') as typeof import('./rag/ManualRenderContext');\n            return renderManualContext(response.manualContext);\n        } catch (error: any) {\n            console.warn(\n                '[IntelligenceEngine] Universal Mode RAG retrieval failed; proceeding without mode evidence:',\n                error?.message ?? error,\n            );\n            return '';\n        }\n    }\n\n`;
if (!s.includes(helperAnchor)) throw new Error('Change 51 anchor missing: V3 retrieval section');
if (!s.includes('private async retrieveUniversalModeContext(')) s = s.replace(helperAnchor, helper + helperAnchor);

const oldPrefetch = `            // Governed document turns resolve through EvidenceResolver inside\n            // WhatToAnswerLLM. Do not start the legacy prefetch in parallel: even\n            // an ignored retrieval is an unauthorized competing evidence path.\n            const modeContextPromise: Promise<string> = options?.activeSkill || docGroundedEnforcementActive || !wtaPrefetchDecision.allowed\n                ? Promise.resolve('') // skill/governed-document mode skips legacy retrieval; blind turn (no user-originated query) skips it too\n                : (async () => {\n                    try {\n                        const { ModesManager } = require('./services/ModesManager') as typeof import('./services/ModesManager');\n                        const mm = ModesManager.getInstance();\n                        if (typeof mm.buildRetrievedActiveModeContextBlockHybrid === 'function') {\n                            // pinnedModeId (#6): parallel-prefetch reads the SAME mode captured\n                            // at t0, so a mid-request mode switch can't mismatch retrieval.\n                            // Phase 3: allowRerank on the LIVE prefetch path only when\n                            // ragSpeculativeRerank is on. The reranker is prewarmed at\n                            // mode activation and this prefetch is consumed under the\n                            // caller's raceWithBudget — so a (warm) rerank costs ~tens of\n                            // ms and an overrun falls through to the non-reranked block.\n                            let allowRerank = false;\n                            try {\n                                // eslint-disable-next-line @typescript-eslint/no-var-requires\n                                const { isRagSpeculativeRerankEnabled } = require('./intelligence/intelligenceFlags');\n                                allowRerank = isRagSpeculativeRerankEnabled();\n                            } catch { /* flag module unavailable → no rerank */ }\n                            return await mm.buildRetrievedActiveModeContextBlockHybrid(\n                                wtaPrefetchQuery, preparedTranscript, 1800, wtaPrefetchAnswerType, true, snapshotModeInfo?.id, allowRerank,\n                                docGroundedEnforcementActive ? { forceDocumentGrounding: true } : undefined,\n                            );\n                        }\n                        return '';\n                    } catch { return ''; }\n                })();\n`;
const newPrefetch = `            // Governed document turns resolve through EvidenceResolver inside\n            // WhatToAnswerLLM. Do not start a competing legacy retrieval path.\n            // Normal application retrieval, when allowed, goes through the same\n            // application-owned universal RAGManager used by WTA/manual chat.\n            const modeContextPromise: Promise<string> = options?.activeSkill || docGroundedEnforcementActive || !wtaPrefetchDecision.allowed\n                ? Promise.resolve('')\n                : this.retrieveUniversalModeContext(wtaPrefetchQuery, snapshotModeInfo?.id, {\n                    tokenBudget: 1800,\n                    allowRerank: (() => {\n                        try {\n                            const { isRagSpeculativeRerankEnabled } = require('./intelligence/intelligenceFlags');\n                            return isRagSpeculativeRerankEnabled();\n                        } catch { return false; }\n                    })(),\n                    answerType: wtaPrefetchAnswerType,\n                    forceDocumentGrounding: docGroundedEnforcementActive,\n                });\n`;
if (!s.includes(oldPrefetch)) throw new Error('Change 51 old prefetch block not found');
s = s.replace(oldPrefetch, newPrefetch);

const oldDoc = `                        const { ModesManager } = require('./services/ModesManager') as typeof import('./services/ModesManager');\n                        const mm = ModesManager.getInstance();\n                        const buildDocContext = async (relaxed: boolean): Promise<string> => {\n                            const opts = {\n                                forceDocumentGrounding: true,\n                                followUpReferentHint: temporalContext?.previousResponses?.slice(-1)?.[0],\n                                ...(relaxed ? { relaxed: true, topK: 24 } : {}),\n                            };\n                            if (typeof mm.buildRetrievedActiveModeContextBlockHybrid === 'function') {\n                                return await mm.buildRetrievedActiveModeContextBlockHybrid(\n                                    docQuestion,\n                                    preparedTranscript,\n                                    relaxed ? 5200 : undefined,\n                                    answerPlan.answerType,\n                                    true,\n                                    requestSnapshot.modeUniqueId,\n                                    true,\n                                    opts,\n                                );\n                            }\n                            return mm.buildRetrievedActiveModeContextBlock(\n                                docQuestion,\n                                preparedTranscript,\n                                relaxed ? 5200 : undefined,\n                                answerPlan.answerType,\n                                true,\n                                requestSnapshot.modeUniqueId,\n                                opts,\n                            );\n                        };\n`;
const newDoc = `                        const buildDocContext = async (relaxed: boolean): Promise<string> => (\n                            this.retrieveUniversalModeContext(docQuestion, requestSnapshot.modeUniqueId, {\n                                forceDocumentGrounding: true,\n                                followUpReferentHint: temporalContext?.previousResponses?.slice(-1)?.[0],\n                                tokenBudget: relaxed ? 5200 : 1800,\n                                topK: relaxed ? 24 : undefined,\n                                allowRerank: true,\n                                answerType: answerPlan.answerType,\n                            })\n                        );\n`;
if (!s.includes(oldDoc)) throw new Error('Change 51 document validator retrieval block not found');
s = s.replace(oldDoc, newDoc);

fs.writeFileSync(file, s);
console.log('Change 51 IntelligenceEngine universal RAG boundary applied.');
